package sml

// dlmsUnits maps DLMS unit codes (per ISO EN 62056-62) to their unit strings.
// Populated from libsml's examples/unit.h. Zero values ("") mean unknown/undefined.
var dlmsUnits [256]string

func init() {
	dlmsUnits[1] = "a"
	dlmsUnits[2] = "mo"
	dlmsUnits[3] = "wk"
	dlmsUnits[4] = "d"
	dlmsUnits[5] = "h"
	dlmsUnits[6] = "min."
	dlmsUnits[7] = "s"
	dlmsUnits[8] = "°"
	dlmsUnits[9] = "°C"
	dlmsUnits[10] = "currency"
	dlmsUnits[11] = "m"
	dlmsUnits[12] = "m/s"
	dlmsUnits[13] = "m³"
	dlmsUnits[14] = "m³"
	dlmsUnits[15] = "m³/h"
	dlmsUnits[16] = "m³/h"
	dlmsUnits[17] = "m³/d"
	dlmsUnits[18] = "m³/d"
	dlmsUnits[19] = "l"
	dlmsUnits[20] = "kg"
	dlmsUnits[21] = "N"
	dlmsUnits[22] = "Nm"
	dlmsUnits[23] = "Pa"
	dlmsUnits[24] = "bar"
	dlmsUnits[25] = "J"
	dlmsUnits[26] = "J/h"
	dlmsUnits[27] = "W"
	dlmsUnits[28] = "VA"
	dlmsUnits[29] = "var"
	dlmsUnits[30] = "Wh"
	dlmsUnits[31] = "VAh"
	dlmsUnits[32] = "varh"
	dlmsUnits[33] = "A"
	dlmsUnits[34] = "C"
	dlmsUnits[35] = "V"
	dlmsUnits[36] = "V/m"
	dlmsUnits[37] = "F"
	dlmsUnits[38] = "Ω"
	dlmsUnits[39] = "Ωm²/m"
	dlmsUnits[40] = "Wb"
	dlmsUnits[41] = "T"
	dlmsUnits[42] = "A/m"
	dlmsUnits[43] = "H"
	dlmsUnits[44] = "Hz"
	dlmsUnits[45] = "1/(Wh)"
	dlmsUnits[46] = "1/(varh)"
	dlmsUnits[47] = "1/(VAh)"
	dlmsUnits[48] = "V²h"
	dlmsUnits[49] = "A²h"
	dlmsUnits[50] = "kg/s"
	dlmsUnits[51] = "S, mho"
	dlmsUnits[52] = "K"
	dlmsUnits[53] = "1/(V²h)"
	dlmsUnits[54] = "1/(A²h)"
	dlmsUnits[55] = "1/m³"
	dlmsUnits[56] = "%"
	dlmsUnits[57] = "Ah"
	dlmsUnits[60] = "Wh/m³"
	dlmsUnits[61] = "J/m³"
	dlmsUnits[62] = "Mol %"
	dlmsUnits[63] = "g/m³"
	dlmsUnits[64] = "Pa s"
	dlmsUnits[253] = "(reserved)"
	dlmsUnits[254] = "(other)"
	dlmsUnits[255] = "(unitless)"
}

// UnitName returns the DLMS unit string for the given code.
// Returns "" for unknown codes.
func UnitName(code uint8) string {
	return dlmsUnits[code]
}
